default_view:
  view: yes
  icon: mdi:home-assistant
  entities:
    - group.family
    - group.lights
    - group.motion
    - group.weather

cameras:
  view: yes
  icon: mdi:cctv
  entities:
    - group.camera_hall
    - group.camera_landing
    - group.camera_drive
    - group.camera_garden
    - group.camera_thomas
    - group.camera_controls

remote:
  view: yes
  icon: mdi:remote
  entities:
    - group.bedroom_remote
    - media_player.bedroom
    - group.living_room_remote

rooms:
  view: yes
  entities:
    - group.bedroom
    - group.office
    - group.thomas
    - group.diningroom

network:
  view: yes
  entities:
    - group.pi_status
    - group.processes
    - group.batteries
    - group.links
    - group.pihole_stats

automation:
view: yes
  entities:
    - automation.alert_on_bad_logon_attempts
    - automation.disable_internal_camera_recording
    - automation.disable_security_when_someone_comes_home
    - automation.enable_internal_camera_recording
    - automation.enable_security_and_send_notification_when_house_becomes_empty
    - automation.low_battery_alert
    - automation.low_outside_temperature
    - automation.motion_alert
    - automation.startup_notification
    - automation.turn_off_christmas_lights_at_midnight
    - automation.turn_off_electric_blanket_at_11pm
    - automation.turn_off_hall_lights_when_there_is_no_longer_any_motion
    - automation.turn_off_office_lights_when_there_is_no_longer_any_motion
    - automation.turn_on_christmas_lights_at_sunset
    - automation.turn_on_electric_blanket_at_630pm
    - automation.turn_on_hall_lights_on_motion
    - automation.turn_on_office_lights_on_motion
    - automation.update_notifications

camera_thomas:
  entities:
    - camera.thomas

camera_hall:
  entities:
    - camera.hall

camera_landing:
  entities:
    - camera.landing

camera_drive:
  entities:
    - camera.drive

camera_garden:
  entities:
    - camera.garden

camera_controls:
  entities:
    - script.camera_thomas_bed
    - script.camera_thomas_door
    - script.camera_thomas_floor

all_motion_sensors:
  entities:
    - binary_sensor.thomas_sensor
    - binary_sensor.office_sensor
    - binary_sensor.hall_motion
    - binary_sensor.landing_motion
    - binary_sensor.nodemcu1

links:
  entities:
    - weblink.foscam_drive
    - weblink.foscam_garden
    - weblink.foscam_hall
    - weblink.foscam_thomas
    - weblink.pihole
    - weblink.router
    - weblink.transmission

motion:
  entities:
    - input_boolean.enable_security
    - binary_sensor.thomas_sensor
    - binary_sensor.office_sensor
    - binary_sensor.hall_motion
    - binary_sensor.landing_motion
    - binary_sensor.nodemcu1

lights:
  entities:
    - light.bedroom
    - light.dining_room
    - light.downstairs_toilet
    - light.hall
    - light.living_room_play_area
    - light.living_room_tv_area
    - switch.desk_lights_switch
    - switch.christmas_lights
    - sensor.lights_on_count

bedroom:
  entities:
    - media_player.bedroom
    - light.bedroom
    - binary_sensor.nodemcu1
    - switch.electric_blanket

diningroom:
  entities:
    - light.dining_room

batteries:
  entities:
    - sensor.gregs_iphone_8_battery_level
    - sensor.gregs_ipad_battery_level
    - sensor.lynette_iphone_battery_level
    - sensor.tradfri_remote_control
    - sensor.tradfri_remote_control_2
    - sensor.fibaro_office_battery_level
    - sensor.fibaro_thomas_battery_level

weather:
  entities:
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_summary

thomas:
  entities:
    - binary_sensor.thomas_sensor
    - sensor.thomas_temperature
    - sensor.thomas_luminance

office:
  entities:
    - switch.desk_lights_switch
    - binary_sensor.office_sensor
    - light.backlights
    - sensor.office_temperature
    - sensor.office_luminance

family:
  entities:
    - device_tracker.gregs_iphone_8
    - device_tracker.lynette_iphone

pi_status:
  name: Server Status
  entities:
    - sensor.since_last_boot
    - sensor.ha_uptime
    - sensor.ram_used
    - sensor.cpu_temperature
    - sensor.disk_used_
    - sensor.disk_used_mnt
    - sensor.speedtest_download
    - sensor.last_backup
    - group.load

load:
  name: Load
  entities:
    - sensor.average_load_1m
    - sensor.average_load_5m
    - sensor.average_load_15m

pihole_stats:
  name: PiHole Stats
  entities:
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_unique_clients
    
processes:
  entities:
    - sensor.process_transmissiondaemon
    - sensor.process_openvpn
    - sensor.process_plex_media_server
    - sensor.process_pureftpd
    - sensor.process_homebridge

bedroom_remote:
  entities:
  - script.bedroom_remote_control

living_room_remote:
  entities:
  - script.living_room_remote_control